"""facts table

Revision ID: db93272d6b89
Revises: e9e16aa78e5c
Create Date: 2022-04-11 13:29:51.184590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db93272d6b89'
down_revision = 'e9e16aa78e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left', sa.String(length=140), nullable=True),
    sa.Column('rel', sa.String(length=140), nullable=True),
    sa.Column('right', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_timestamp'), 'fact', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_timestamp'), table_name='fact')
    op.drop_table('fact')
    # ### end Alembic commands ###
